apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-db
spec:
  template:
    spec:
      volumes:
      - $patch: delete
        name: metadata-mysql
      - name: metadata-mysql
        emptyDir: {}  
